config/routes.rb
# frozen_string_literal: true
require 'sidekiq/web'

# 127.0.0.1 uglst.dev
# 127.0.0.1 api.uglst.dev

Rails.application.routes.draw do
  use_doorkeeper

  resources :opportunities, only: %i(index show)

  # /status
  get '/status', to: 'status#ping'

  # /heartbeat
  get '/heartbeat.:format', to: 'heartbeat#ping', constraints: { format: 'txt' }

  get 'reports/top_viewed_user_groups.:format', to: 'reports#top_viewed_user_groups', constraints: { format: 'json' }

  namespace :happy do
    get 'hello/badge'
  end

  authenticate :user, ->(u) { Rails.env.development? || u.admin? } do
    namespace :admin, path: '/admin' do # , constraints: require_admin do
      mount Sidekiq::Web, at: 'sidekiq'
      mount PgHero::Engine, at: 'pghero'
      mount RailsAdmin::Engine, at: 'rails'
    end
  end

  namespace :api, path: '/', constraints: { subdomain: 'api' } do
    namespace :v1 do
      get '/me' => 'credentials#me'
    end
  end

  # /privacy
  get 'privacy' => 'pages#privacy'

  # /terms_of_service
  get 'terms_of_service' => 'pages#terms_of_service'

  post 'awesome' => 'pages#awesome'

  # /networks
  resources :networks

  resources :profiles, except: %(edit update destroy) do
    scope module: :profiles do
      # /profiles/:id/account
      resource :account, only: %i(edit update)

      # /profiles/:id/private
      resource :private, only: %i(edit update destroy)

      # /profiles/:id/public
      resource :public, only: %i(edit update)
    end
  end

  # /users
  devise_for :users

  resources :user_groups do
    # /user_groups/:id/join
    post '/join' => 'user_groups#join'

    # /user_groups/:id/leave
    post '/leave' => 'user_groups#leave'

    # /user_groups/:id/memberships
    get '/memberships' => 'user_groups#memberships'
  end

  # /
  root 'user_groups#index'
end

# == Route Map
#
#                        Prefix Verb   URI Pattern                                       Controller#Action
#                               GET    /oauth/authorize/:code(.:format)                  doorkeeper/authorizations#show
#           oauth_authorization GET    /oauth/authorize(.:format)                        doorkeeper/authorizations#new
#                               POST   /oauth/authorize(.:format)                        doorkeeper/authorizations#create
#                               DELETE /oauth/authorize(.:format)                        doorkeeper/authorizations#destroy
#                   oauth_token POST   /oauth/token(.:format)                            doorkeeper/tokens#create
#                  oauth_revoke POST   /oauth/revoke(.:format)                           doorkeeper/tokens#revoke
#            oauth_applications GET    /oauth/applications(.:format)                     doorkeeper/applications#index
#                               POST   /oauth/applications(.:format)                     doorkeeper/applications#create
#         new_oauth_application GET    /oauth/applications/new(.:format)                 doorkeeper/applications#new
#        edit_oauth_application GET    /oauth/applications/:id/edit(.:format)            doorkeeper/applications#edit
#             oauth_application GET    /oauth/applications/:id(.:format)                 doorkeeper/applications#show
#                               PATCH  /oauth/applications/:id(.:format)                 doorkeeper/applications#update
#                               PUT    /oauth/applications/:id(.:format)                 doorkeeper/applications#update
#                               DELETE /oauth/applications/:id(.:format)                 doorkeeper/applications#destroy
# oauth_authorized_applications GET    /oauth/authorized_applications(.:format)          doorkeeper/authorized_applications#index
#  oauth_authorized_application DELETE /oauth/authorized_applications/:id(.:format)      doorkeeper/authorized_applications#destroy
#              oauth_token_info GET    /oauth/token/info(.:format)                       doorkeeper/token_info#show
#                 opportunities GET    /opportunities(.:format)                          opportunities#index
#                   opportunity GET    /opportunities/:id(.:format)                      opportunities#show
#                        status GET    /status(.:format)                                 status#ping
#                               GET    /heartbeat.:format                                heartbeat#ping {:format=>"txt"}
#                               GET    /reports/top_viewed_user_groups.:format           reports#top_viewed_user_groups {:format=>"json"}
#             happy_hello_badge GET    /happy/hello/badge(.:format)                      happy/hello#badge
#             admin_sidekiq_web        /admin/sidekiq                                    Sidekiq::Web
#                 admin_pg_hero        /admin/pghero                                     PgHero::Engine
#             admin_rails_admin        /admin/rails                                      RailsAdmin::Engine
#                     api_v1_me GET    /v1/me(.:format)                                  api/v1/credentials#me {:subdomain=>"api"}
#                       privacy GET    /privacy(.:format)                                pages#privacy
#              terms_of_service GET    /terms_of_service(.:format)                       pages#terms_of_service
#                       awesome POST   /awesome(.:format)                                pages#awesome
#                      networks GET    /networks(.:format)                               networks#index
#                               POST   /networks(.:format)                               networks#create
#                   new_network GET    /networks/new(.:format)                           networks#new
#                  edit_network GET    /networks/:id/edit(.:format)                      networks#edit
#                       network GET    /networks/:id(.:format)                           networks#show
#                               PATCH  /networks/:id(.:format)                           networks#update
#                               PUT    /networks/:id(.:format)                           networks#update
#                               DELETE /networks/:id(.:format)                           networks#destroy
#          edit_profile_account GET    /profiles/:profile_id/account/edit(.:format)      profiles/account#edit
#               profile_account PATCH  /profiles/:profile_id/account(.:format)           profiles/account#update
#                               PUT    /profiles/:profile_id/account(.:format)           profiles/account#update
#          edit_profile_private GET    /profiles/:profile_id/private/edit(.:format)      profiles/private#edit
#               profile_private PATCH  /profiles/:profile_id/private(.:format)           profiles/private#update
#                               PUT    /profiles/:profile_id/private(.:format)           profiles/private#update
#                               DELETE /profiles/:profile_id/private(.:format)           profiles/private#destroy
#           edit_profile_public GET    /profiles/:profile_id/public/edit(.:format)       profiles/public#edit
#                profile_public PATCH  /profiles/:profile_id/public(.:format)            profiles/public#update
#                               PUT    /profiles/:profile_id/public(.:format)            profiles/public#update
#                      profiles GET    /profiles(.:format)                               profiles#index
#                               POST   /profiles(.:format)                               profiles#create
#                   new_profile GET    /profiles/new(.:format)                           profiles#new
#                  edit_profile GET    /profiles/:id/edit(.:format)                      profiles#edit
#                       profile GET    /profiles/:id(.:format)                           profiles#show
#                               PATCH  /profiles/:id(.:format)                           profiles#update
#                               PUT    /profiles/:id(.:format)                           profiles#update
#                               DELETE /profiles/:id(.:format)                           profiles#destroy
#              new_user_session GET    /users/sign_in(.:format)                          devise/sessions#new
#                  user_session POST   /users/sign_in(.:format)                          devise/sessions#create
#          destroy_user_session DELETE /users/sign_out(.:format)                         devise/sessions#destroy
#                 user_password POST   /users/password(.:format)                         devise/passwords#create
#             new_user_password GET    /users/password/new(.:format)                     devise/passwords#new
#            edit_user_password GET    /users/password/edit(.:format)                    devise/passwords#edit
#                               PATCH  /users/password(.:format)                         devise/passwords#update
#                               PUT    /users/password(.:format)                         devise/passwords#update
#      cancel_user_registration GET    /users/cancel(.:format)                           devise/registrations#cancel
#             user_registration POST   /users(.:format)                                  devise/registrations#create
#         new_user_registration GET    /users/sign_up(.:format)                          devise/registrations#new
#        edit_user_registration GET    /users/edit(.:format)                             devise/registrations#edit
#                               PATCH  /users(.:format)                                  devise/registrations#update
#                               PUT    /users(.:format)                                  devise/registrations#update
#                               DELETE /users(.:format)                                  devise/registrations#destroy

app/models/network.rb
# frozen_string_literal: true
class Network < ActiveRecord::Base
  include Twitterable

  include PublicActivity::Model
  tracked owner: proc { |controller, _model| controller.current_user }

  has_paper_trail

  include PgSearch
  pg_search_scope :search_for,
                  against: %i(name description),
                  using: %i(tsearch trigram)

  extend FriendlyId
  friendly_id :name, use: :slugged

  mount_uploader :logo, NetworkLogoUploader

  default_scope { order('created_at ASC') }

  belongs_to :registered_by, class_name: 'User', foreign_key: 'registered_by_id'

  has_many :network_affiliations
  has_many :user_groups, through: :network_affiliations

  validates :name, presence: true, uniqueness: true, length: { minimum: 8, maximum: 64 }, allow_blank: false
end

# == Schema Information
#
# Table name: networks
#
#  id               :uuid             not null, primary key
#  registered_by_id :uuid
#  homepage         :string
#  name             :text
#  slug             :string
#  twitter          :string
#  description      :text
#  logo             :string
#  created_at       :datetime
#  updated_at       :datetime
#

app/controllers/networks_controller.rb
# frozen_string_literal: true
class NetworksController < ApplicationController
  before_action :set_network, only: %i(show edit update destroy join leave)
  before_action :authenticate_user!, only: %i(new edit update destroy join leave)

  def show
    @page_title = "#{@network.name} on Network List" if @network && @network.name
  end

  def index
    @networks = Network.order('created_at').reverse_order
    respond_to do |format|
      format.html { render :index }
      format.rss { render layout: nil }
    end
  end

  def edit
  end

  def new
    @network = current_user.networks_registered.build
  end

  def create
    @network = current_user.networks_registered.build(network_params)

    respond_to do |format|
      if @network.save
        format.html { redirect_to @network, notice: 'Network was successfully created.' }
        format.json { render :show, status: :created, location: @network }
      else
        format.html { render :new }
        format.json { render json: @network.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    unless current_user.admin? || @network.registered_by.id == current_user.id
      raise 'You may only update networks that you registered.'
    end

    respond_to do |format|
      if @network.update(network_params)
        format.html { redirect_to @network, notice: 'Network was successfully updated.' }
        format.json { render :show, status: :ok, location: @network }
      else
        format.html { render :edit }
        format.json { render json: @network.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    unless current_user.admin? || @network.registered_by.id == current_user.id
      raise 'You may only destroy Networks that you registered.'
    end

    @network.destroy

    respond_to do |format|
      format.html { redirect_to networks_url, notice: 'Network was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  def set_network
    @network = Network.friendly.find(params[:id])
  end

  def network_params
    if current_user.admin?
      params.require(:network).permit!
    else
      params.require(:network).permit(
        :description,
        :homepage,
        :name,
        :twitter,
        :logo
      )
    end
  end
end

app/views/networks/_form.html.haml
= simple_form_for(@network) do |f|
  = f.error_notification
  = field_set_tag 'Network Info' do
    = f.input :name
    = f.input :description
    = image_tag(@network.logo_url, class: '', style: 'max-height: 100px; max-width: 100px;')
    = f.input :logo
  = field_set_tag 'Online Info' do
    = f.input :homepage, placeholder: 'http://www.ugtastic.com'
    = f.input :twitter, placeholder: 'https://twitter.com/ugtastic'
  - if current_user && current_user.admin?
    = field_set_tag 'Admin Fields' do
      = f.input :slug, disabled: true
      = f.input :registered_by_id, collection: User.all.select(:id, :username), value_method: :id, label_method: :username, selected: @network.registered_by_id
  = f.button :submit

app/views/networks/edit.html.haml
%h1 Edit your User-Group Network
= render 'form'

app/views/networks/index.html.haml
= content_for(:rss) do
  = auto_discovery_link_tag(:rss, networks_url(format: :rss))
= content_for :breadcrumb do
  %li User-Group Networks
= content_for :twitter_card do
  %meta{content: 'summary', name: 'twitter:card'}
  %meta{content: '@uglst', name: 'twitter:site'}
  %meta{content: 'User-Group List', name: 'twitter:title'}
  %meta{content: 'Discover User-Group community in your backyard and around the world on UGl.st', name: 'twitter:description'}
  %meta{content: '@uglst', name: 'twitter:creator'}
  %meta{content: 'https://pbs.twimg.com/profile_images/2343634389/isvctl4ndfajfittw3px.png', name: 'twitter:image:src'}
  %meta{content: 'https://ugl.st', name: 'twitter:domain'}
%ul.media-list
  - @networks.each do |network|
    %li.media
      = link_to network, class: 'pull-left' do
        = image_tag network.logo.present? ? network.logo_url : 'network_avatar_fallback.png', class: 'media-object', style: 'max-height: 64px; max-width: 64px;'
      .media-body
        %h4= network.name
        %p.description= Sanitize.clean(network.description, Sanitize::Config::BASIC).truncate(140)
        %div{style: 'margin-top: 8px;'}= link_to 'Full-profile', network

app/views/networks/new.html.haml
%h1 Register a new User-Group Network
= render 'form'
= link_to 'Back', networks_path

app/views/networks/show.html.haml
= content_for :breadcrumb do
  %li= link_to 'User-Group Networks', networks_path
  %li= @network.name
= content_for :twitter_card do
  %meta{content: "summary", name: 'twitter:card'}
  %meta{content: "@uglst", name: 'twitter:site'}
  %meta{content: @network.name, name: 'twitter:title'}
  %meta{content: @network.description.to_s.truncate(195), name: 'twitter:description'}
  %meta{content: "@#{@network.twitter}", name: 'twitter:creator'}
  %meta{content: (@network.logo.present? ? @network.logo_url : 'network_avatar_fallback.png'), name: 'twitter:image:src'}
  %meta{content: "ugl.st", name: "twitter:domain"}
- if current_user && (current_user.admin? || current_user == @network.registered_by)
  .col-sm-6.well.col-sm-offset-3
    .btn-group
      %button.btn.btn-default.dropdown-toggle{"data-toggle" => "dropdown", type: "button"}
        Manage User-Group Network
        %span.caret
      %ul.dropdown-menu{role: "menu"}
        %li= link_to 'Edit', edit_network_path(@network)
        %li= link_to 'Destroy', @network, method: :delete, data: {confirm: 'Are you sure?'}
.col-sm-6.well.col-sm-offset-3{itemscope: "", itemtype: "https://schema.org/LocalBusiness"}
  %center
    = image_tag(@network.logo.present? ? @network.logo_url : 'network_avatar_fallback.png', class: 'media-object', style: 'max-height: 192px; max-width: 192px;', 'itemprop' => 'image')
    %h3{itemprop: "name"}= @network.name
    %hr{style: "border-color: transparent;"}
    %p
      %em= Sanitize.clean(@network.description, Sanitize::Config::BASIC)
    %hr/
    = link_to @network.homepage, target: '_blank', 'itemprop' => 'url' do
      %span.glyphicons.home
      = @network.name
      Homepage
#user_group_members.col-sm-6.well.col-sm-offset-3
  %h4 Affiliated User-Groups:
  %ul.media-list
    - if @network.user_groups.empty?
      No User-Groups affiliated with #{@network.name}
    - else
      - @network.user_groups.each do |ug|
        %li.media
          = link_to user_group_path(ug), class: 'pull-left' do
            = image_tag(ug.logo.present? ? ug.logo_url : 'user_group_avatar_fallback.png', class: 'media-object', style: 'max-height: 64px; max-width: 64px;', 'itemprop' => 'image')
          .media-body
            %h4= link_to ug.name, user_group_path(ug)
            %p.description= Sanitize.clean(ug.description || '', Sanitize::Config::BASIC).truncate(64)