config/routes.rb
# frozen_string_literal: true
require 'sidekiq/web'

# 127.0.0.1 uglst.dev
# 127.0.0.1 api.uglst.dev

Rails.application.routes.draw do
  use_doorkeeper

  resources :opportunities, only: %i(index show)

  # /status
  get '/status', to: 'status#ping'

  # /heartbeat
  get '/heartbeat.:format', to: 'heartbeat#ping', constraints: { format: 'txt' }

  get 'reports/top_viewed_user_groups.:format', to: 'reports#top_viewed_user_groups', constraints: { format: 'json' }

  namespace :happy do
    get 'hello/badge'
  end

  authenticate :user, ->(u) { Rails.env.development? || u.admin? } do
    namespace :admin, path: '/admin' do # , constraints: require_admin do
      mount Sidekiq::Web, at: 'sidekiq'
      mount PgHero::Engine, at: 'pghero'
      mount RailsAdmin::Engine, at: 'rails'
    end
  end

  namespace :api, path: '/', constraints: { subdomain: 'api' } do
    namespace :v1 do
      get '/me' => 'credentials#me'
    end
  end

  # /privacy
  get 'privacy' => 'pages#privacy'

  # /terms_of_service
  get 'terms_of_service' => 'pages#terms_of_service'

  post 'awesome' => 'pages#awesome'

  # /networks
  resources :networks

  resources :profiles, except: %(edit update destroy) do
    scope module: :profiles do
      # /profiles/:id/account
      resource :account, only: %i(edit update)

      # /profiles/:id/private
      resource :private, only: %i(edit update destroy)

      # /profiles/:id/public
      resource :public, only: %i(edit update)
    end
  end

  # /users
  devise_for :users

  resources :user_groups do
    # /user_groups/:id/join
    post '/join' => 'user_groups#join'

    # /user_groups/:id/leave
    post '/leave' => 'user_groups#leave'

    # /user_groups/:id/memberships
    get '/memberships' => 'user_groups#memberships'
  end

  # /
  root 'user_groups#index'
end

# == Route Map
#
#                        Prefix Verb   URI Pattern                                       Controller#Action
#                               GET    /oauth/authorize/:code(.:format)                  doorkeeper/authorizations#show
#           oauth_authorization GET    /oauth/authorize(.:format)                        doorkeeper/authorizations#new
#                               POST   /oauth/authorize(.:format)                        doorkeeper/authorizations#create
#                               DELETE /oauth/authorize(.:format)                        doorkeeper/authorizations#destroy
#                   oauth_token POST   /oauth/token(.:format)                            doorkeeper/tokens#create
#                  oauth_revoke POST   /oauth/revoke(.:format)                           doorkeeper/tokens#revoke
#            oauth_applications GET    /oauth/applications(.:format)                     doorkeeper/applications#index
#                               POST   /oauth/applications(.:format)                     doorkeeper/applications#create
#         new_oauth_application GET    /oauth/applications/new(.:format)                 doorkeeper/applications#new
#        edit_oauth_application GET    /oauth/applications/:id/edit(.:format)            doorkeeper/applications#edit
#             oauth_application GET    /oauth/applications/:id(.:format)                 doorkeeper/applications#show
#                               PATCH  /oauth/applications/:id(.:format)                 doorkeeper/applications#update
#                               PUT    /oauth/applications/:id(.:format)                 doorkeeper/applications#update
#                               DELETE /oauth/applications/:id(.:format)                 doorkeeper/applications#destroy
# oauth_authorized_applications GET    /oauth/authorized_applications(.:format)          doorkeeper/authorized_applications#index
#  oauth_authorized_application DELETE /oauth/authorized_applications/:id(.:format)      doorkeeper/authorized_applications#destroy
#              oauth_token_info GET    /oauth/token/info(.:format)                       doorkeeper/token_info#show
#                 opportunities GET    /opportunities(.:format)                          opportunities#index
#                   opportunity GET    /opportunities/:id(.:format)                      opportunities#show
#                        status GET    /status(.:format)                                 status#ping
#                               GET    /heartbeat.:format                                heartbeat#ping {:format=>"txt"}
#                               GET    /reports/top_viewed_user_groups.:format           reports#top_viewed_user_groups {:format=>"json"}
#             happy_hello_badge GET    /happy/hello/badge(.:format)                      happy/hello#badge
#             admin_sidekiq_web        /admin/sidekiq                                    Sidekiq::Web
#                 admin_pg_hero        /admin/pghero                                     PgHero::Engine
#             admin_rails_admin        /admin/rails                                      RailsAdmin::Engine
#                     api_v1_me GET    /v1/me(.:format)                                  api/v1/credentials#me {:subdomain=>"api"}
#                       privacy GET    /privacy(.:format)                                pages#privacy
#              terms_of_service GET    /terms_of_service(.:format)                       pages#terms_of_service
#                       awesome POST   /awesome(.:format)                                pages#awesome
#                      networks GET    /networks(.:format)                               networks#index
#                               POST   /networks(.:format)                               networks#create
#                   new_network GET    /networks/new(.:format)                           networks#new
#                  edit_network GET    /networks/:id/edit(.:format)                      networks#edit
#                       network GET    /networks/:id(.:format)                           networks#show
#                               PATCH  /networks/:id(.:format)                           networks#update
#                               PUT    /networks/:id(.:format)                           networks#update
#                               DELETE /networks/:id(.:format)                           networks#destroy
#          edit_profile_account GET    /profiles/:profile_id/account/edit(.:format)      profiles/account#edit
#               profile_account PATCH  /profiles/:profile_id/account(.:format)           profiles/account#update
#                               PUT    /profiles/:profile_id/account(.:format)           profiles/account#update
#          edit_profile_private GET    /profiles/:profile_id/private/edit(.:format)      profiles/private#edit
#               profile_private PATCH  /profiles/:profile_id/private(.:format)           profiles/private#update
#                               PUT    /profiles/:profile_id/private(.:format)           profiles/private#update
#                               DELETE /profiles/:profile_id/private(.:format)           profiles/private#destroy
#           edit_profile_public GET    /profiles/:profile_id/public/edit(.:format)       profiles/public#edit
#                profile_public PATCH  /profiles/:profile_id/public(.:format)            profiles/public#update
#                               PUT    /profiles/:profile_id/public(.:format)            profiles/public#update
#                      profiles GET    /profiles(.:format)                               profiles#index
#                               POST   /profiles(.:format)                               profiles#create
#                   new_profile GET    /profiles/new(.:format)                           profiles#new
#                  edit_profile GET    /profiles/:id/edit(.:format)                      profiles#edit
#                       profile GET    /profiles/:id(.:format)                           profiles#show
#                               PATCH  /profiles/:id(.:format)                           profiles#update
#                               PUT    /profiles/:id(.:format)                           profiles#update
#                               DELETE /profiles/:id(.:format)                           profiles#destroy
#              new_user_session GET    /users/sign_in(.:format)                          devise/sessions#new
#                  user_session POST   /users/sign_in(.:format)                          devise/sessions#create
#          destroy_user_session DELETE /users/sign_out(.:format)                         devise/sessions#destroy
#                 user_password POST   /users/password(.:format)                         devise/passwords#create
#             new_user_password GET    /users/password/new(.:format)                     devise/passwords#new
#            edit_user_password GET    /users/password/edit(.:format)                    devise/passwords#edit
#                               PATCH  /users/password(.:format)                         devise/passwords#update
#                               PUT    /users/password(.:format)                         devise/passwords#update
#      cancel_user_registration GET    /users/cancel(.:format)                           devise/registrations#cancel
#             user_registration POST   /users(.:format)                                  devise/registrations#create
#         new_user_registration GET    /users/sign_up(.:format)                          devise/registrations#new
#        edit_user_registration GET    /users/edit(.:format)                             devise/registrations#edit
#                               PATCH  /users(.:format)                                  devise/registrations#update
#                               PUT    /users(.:format)                                  devise/registrations#update
#                               DELETE /users(.:format)                                  devise/registrations#destroy

app/models/user_group.rb
# frozen_string_literal: true
class UserGroup < ActiveRecord::Base
  include PublicActivity::Model
  tracked owner: proc { |c, _| c && c.current_user ? c.current_user : nil }

  has_paper_trail

  include PgSearch
  pg_search_scope :search_for,
                  against: %i(name description),
                  using: %i(tsearch trigram)

  extend FriendlyId
  friendly_id :slug_candidates, use: %i(slugged)

  mount_uploader :logo, UserGroupLogoUploader

  acts_as_taggable_on :topics

  default_scope { order('created_at ASC') }

  belongs_to :registered_by, class_name: 'User', foreign_key: 'registered_by_id'

  has_many :network_affiliations
  has_many :networks, through: :network_affiliations

  has_many :user_group_memberships
  has_many :users, through: :user_group_memberships

  validates :name, presence: true, length: { minimum: 2, maximum: 64 }, allow_blank: false, uniqueness: true
  validates :description, presence: nil, length: { minimum: 8, maximum: 2048 }, allow_blank: false
  validates :shortname, presence: nil, length: { minimum: 1, maximum: 15 }, allow_blank: true, uniqueness: true

  has_one :user_group_twitter_account
  has_one :twitter_account, through: :user_group_twitter_account

  def user_group_twitter_account
    super || build_user_group_twitter_account
  end

  has_one :user_group_location
  has_one :location, through: :user_group_location

  def user_group_location
    super || build_user_group_location
  end

  def slug_candidates
    shortname.present? ? [:shortname] : [:name]
  end
end

# == Schema Information
#
# Table name: user_groups
#
#  id               :uuid             not null, primary key
#  registered_by_id :uuid
#  homepage         :string
#  name             :string
#  slug             :string
#  description      :text
#  logo             :string
#  created_at       :datetime
#  updated_at       :datetime
#  shortname        :string
#  meetup           :string
#  github           :string
#  facebook         :string
#

app/controllers/user_groups_controller.rb
# frozen_string_literal: true
class UserGroupsController < ApplicationController
  before_action :set_user_group, only: %i(show edit update destroy join leave)
  before_action :authenticate_user!, only: %i(new edit update destroy join leave)
  after_action :send_tweet!, only: :create

  def send_tweet!
    UserGroupTweeterJob.perform_async(@user_group.id) if @user_group.valid? && @user_group.persisted?
  end

  def index
    query = params[:q]
    @user_groups = if query.present?
                     UserGroup.search_for(query).page(params[:page])
                   else
                     UserGroup.order('created_at').reverse_order.page(params[:page])
                   end

    respond_to do |format|
      format.html { render :index }
      format.rss { render layout: nil }
    end
  end

  def show
    @page_title = "#{@user_group.name} on User-Group List" if @user_group && @user_group.name
    memberships
  end

  def new
    @user_group = current_user.user_groups_registered.build
    @user_group.location = Location.new
  end

  def edit
  end

  def create
    model_params = user_group_params.reject { |key| %w(twitter address).include?(key) }

    @user_group = current_user.user_groups_registered.build(model_params)

    address = user_group_params['address']
    @user_group.location = Location.find_or_create_by(address: address)

    twitter_account_screen_name = user_group_params['twitter']

    if twitter_account_screen_name.blank?
      @user_group.twitter_account = nil
    else
      twitter_account = TwitterAccount.where('screen_name ilike ?', twitter_account_screen_name).first
      @user_group.twitter_account = if twitter_account
                                      twitter_account
                                    else
                                      TwitterAccount.create!(screen_name: twitter_account_screen_name)
                                    end
    end

    respond_to do |format|
      if @user_group.save
        format.html { redirect_to @user_group, notice: 'User-Group was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  def update
    unless current_user.admin? || @user_group.registered_by.id == current_user.id
      raise 'You may only update User-Groups that you registered.'
    end

    model_params = user_group_params.reject { |key| %w(twitter address).include?(key) }

    address = user_group_params['address']
    @user_group.location = Location.find_or_create_by(address: address)

    twitter_account_screen_name = user_group_params['twitter']
    if twitter_account_screen_name.blank?
      @user_group.twitter_account = nil
    else
      twitter_account = TwitterAccount.where('screen_name ilike ?', twitter_account_screen_name).first
      @user_group.twitter_account = if twitter_account
                                      twitter_account
                                    else
                                      TwitterAccount.create!(screen_name: twitter_account_screen_name)
                                    end
    end

    respond_to do |format|
      if @user_group.update(model_params)
        format.html { redirect_to @user_group, notice: 'User-Group was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  def destroy
    unless current_user.admin? || @user_group.registered_by.id == current_user.id
      raise 'You may only destroy User-Groups that you registered.'
    end

    @user_group.destroy

    respond_to do |format|
      format.html { redirect_to user_groups_url, notice: 'User-Group was successfully destroyed.' }
    end
  end

  def join
    # 0 == member
    @ugm = UserGroupMembership.create_with(relationship: 0).find_or_create_by(user_id: current_user.id, user_group_id: @user_group.id)
  end

  def leave
    UserGroupMembership.find_by(user_id: current_user.id, user_group_id: @user_group.id, relationship: 0).destroy
  end

  def memberships
    @ugms = UserGroupMembership.includes(:user).where(user_group: @user_group)
  end

  protected

  def set_user_group
    @user_group = UserGroup.friendly.find(params[:id] || params[:user_group_id])
  end

  def user_group_params
    @user_group_params ||= if current_user.admin?
                             params.require(:user_group).permit!
                           else
                             params.require(:user_group).permit(
                               :address,
                               :description,
                               :homepage,
                               :name,
                               :twitter,
                               :topic_list,
                               :logo
                             )
                           end
  end
end

app/views/user_groups/_form.html.haml
= simple_form_for(@user_group) do |f|
  = f.error_notification
  .row
    .col-lg-4
      = field_set_tag 'User-Group Info' do
        = f.input :name
        = f.input :description
        = f.input :topic_list
        = image_tag @user_group.logo_url, class: '', style: 'max-height: 100px; max-width: 100px;'
        = f.input :logo

    .col-lg-4
      = field_set_tag 'Geographic Info' do
        #googlemaps-mini
        = f.input :address, required: true, placeholder: 'City, State/Province Country', hint: 'Example: 614 18th Ave Menlo Park, CA 94025', input_html: { value: @user_group.location.formatted_address }, as: :string
        %p.help-block
          Please enter at least your City, State/Province Country or more precise address info.

    .col-lg-4
      = field_set_tag 'Online Info' do
        = f.input :homepage, placeholder: 'http://www.ugtastic.com'
        = f.input :twitter, placeholder: '@ugtastic', input_html: { value: @user_group.twitter_account.try(:screen_name) }

  .row.well
    .actions= f.submit 'Save User-Group', class: 'btn btn-primary'

app/views/user_groups/_join_leave.html.haml
#user_group_membership
  - if current_user
    - if current_user.user_group_memberships.where(user_group: @user_group).empty?
      = render 'join_link'
    - else
      = render 'leave_link'
  - else
    = link_to "Sign in to join #{@user_group.name}", new_user_session_path

app/views/user_groups/_join_link.html.haml
= link_to user_group_join_path(@user_group), id: 'user_group_join_link', remote: true, method: :post, rel: 'nofollow', data: {disable_with: 'Joining…'} do
  Join #{@user_group.name}

app/views/user_groups/_leave_link.html.haml
= link_to user_group_leave_path(@user_group), id: 'user_group_leave_link', remote: true, method: :post, rel: 'nofollow', data: {disable_with: 'Leaving…'} do
  Leave #{@user_group.name}

app/views/user_groups/_twitter_button.html.haml
- if model.twitter_account.respond_to?(:screen_name)
  %a.twitter-share-button{"data-size" => "large", "data-text" => "Check out #{model.name.strip}'s #UserGroup profile#{model.twitter_account.present? ? " and follow @#{model.twitter_account.screen_name}" : ''}", "data-url" => user_group_url(model), "data-via" => "uglst", href: "https://twitter.com/share"}
    Tweet
    @#{model.twitter_account.screen_name}

  :javascript
    !function (d, s, id) {
        var js, fjs = d.getElementsByTagName(s)[0], p = /^http:/.test(d.location) ? 'http' : 'https';
        if (!d.getElementById(id)) {
          js = d.createElement(s);
          js.id = id;
          js.src = p + '://platform.twitter.com/widgets.js';
          fjs.parentNode.insertBefore(js, fjs);
        }
      }(document, 'script', 'twitter-wjs');

app/views/user_groups/edit.html.haml
%h1 Edit your User-Group
= render 'form'

app/views/user_groups/index.html.haml
= content_for(:rss) do
  = auto_discovery_link_tag(:rss, user_groups_url(format: :rss))

= content_for(:breadcrumb) do
  %li User-Groups

= content_for :twitter_card do
  %meta{content: "summary", name: "twitter:card"}
  %meta{content: "@uglst", name: "twitter:site"}
  %meta{content: "User-Group List", name: "twitter:title"}
  %meta{content: "Discover User-Group community in your backyard and around the world on UGl.st", name: "twitter:description"}
  %meta{content: "@uglst", name: "twitter:creator"}
  %meta{content: "https://pbs.twimg.com/profile_images/2343634389/isvctl4ndfajfittw3px.png", name: "twitter:image:src"}
  %meta{content: "https://ugl.st", name: "twitter:domain"}

- if @user_groups.empty?
  %h3 Uh, oh! Looks like there are no User-Groups registered!

- row_length = 3
- placeholder_shown = false
- @user_groups.in_groups_of(row_length) do |row|
  .row
    - row.each do |user_group|
      - if user_group
        .col-lg-4
          .well(style="height: 264px; position: relative;")
            = link_to user_group, class: 'pull-left' do
              = image_tag user_group.logo.present? ? user_group.logo_url : 'user_group_avatar_fallback.png', class: 'media-object', style: 'max-height: 96px; max-width: 96px; padding-right: 8px; padding-bottom: 4px;'
            %h4= user_group.name
            %p.description
              = Sanitize.clean(user_group.description, Sanitize::Config::BASIC).truncate(144)
            %div(style="text-align: right; position: absolute; bottom: 16px; right: 16px;")
              = link_to user_group, class: 'btn btn-default' do
                %span.glyphicons.zoom_in
                Full Profile
      - else
        - unless placeholder_shown
          - placeholder_shown = true
          - placeholder_span = row_length - row.compact.length
          - if placeholder_span == 1
            .col-lg-4
              .well(style="height: 264px; position: relative;")
                %h2.text-center YOUR USER-GROUP HERE!
                %p.description
                  <strong>YOU</strong> can increase your User-Group's social footprint by adding them to User-Group List. Click to add them now. It's free and quick!
                %div(style="text-align: right; position: absolute; bottom: 16px; right: 16px;")
                  = link_to new_user_group_path, class: 'btn btn-info', style: 'color: white; font-weight: bold' do
                    %span.glyphicons.plus
                    Register your User-Group!
          - elsif placeholder_span == 2
            .col-lg-8
              .well(style="height: 264px; position: relative;")
                %h2.text-center THIS COULD BE YOUR USER-GROUP!
                %p.description
                  <strong>YOU</strong> can increase your User-Group's social footprint by adding them to User-Group List. Click the button and register your favorite User-Group (or more) in seconds.
                %p.description
                  You only need to be a friend of your favorite User-Group to register it on User-Group List. Organizers are welcome to claim the UG later.
                %div(style="text-align: right; position: absolute; bottom: 16px; right: 16px;")
                  = link_to new_user_group_path, class: 'btn btn-info', style: 'color: white; font-weight: bold' do
                    %span.glyphicons.plus
                    Click and add your favorite User-Group!

.row.text-center
  = paginate @user_groups

app/views/user_groups/join.js.haml
$('#user_group_membership').empty();
$('#user_group_membership').append('#{j render 'leave_link'}');

$('#user_group_members');

app/views/user_groups/leave.js.haml
$('#user_group_membership').empty();
$('#user_group_membership').append('#{j render 'join_link'}');

app/views/user_groups/new.html.haml
%h1 Register a new User-Group
= render 'form'
= link_to 'Back', user_groups_path

app/views/user_groups/show.html.haml
= content_for :breadcrumb do
  %li= link_to 'User-Groups', user_groups_path
  %li= @user_group.name
= content_for :twitter_card do
  %meta{content: "summary", name: "twitter:card"}
  %meta{content: "@uglst", name: "twitter:site"}
  %meta{content: @user_group.name, name: "twitter:title"}
  %meta{content: @user_group.description.to_s.truncate(195), name: "twitter:description"}
  - if @user_group.twitter_account
    %meta{content: "@#{@user_group.twitter_account.screen_name}", name: "twitter:creator"}
  %meta{content: (@user_group.logo.present? ? @user_group.logo_url : 'user_group_avatar_fallback.png'), name: 'twitter:image:src'}
  %meta{content: 'ugl.st', name: 'twitter:domain'}

.col-lg-6.well{itemscope: '', itemtype: "https://schema.org/LocalBusiness"}
  = render 'join_leave'
  %center
    = image_tag(@user_group.logo.present? ? @user_group.logo_url : 'user_group_avatar_fallback.png', class: 'media-object', style: 'max-height: 192px; max-width: 192px;', 'itemprop' => 'image')
    %h3{itemprop: "name"}= @user_group.name
    %p.small{itemprop: 'address', itemscope: '', itemtype: 'https://schema.org/PostalAddress'}
      = succeed @user_group.location.city.present? ? ',' : '' do
        %span{itemprop: 'addressLocality'}>= @user_group.location.city
      = succeed @user_group.location.city.blank? && @user_group.location.state_province.present? ? ',' : '' do
        %span{itemprop: 'addressRegion'}>= @user_group.location.state_province
      %span{itemprop: 'addressCountry'}>
        = @user_group.location.country

    %hr{style: 'border-color: transparent;'}

    %p
      %em= Sanitize.clean(@user_group.description, Sanitize::Config::BASIC)
    - if @user_group.topics.present?
      %hr{style: 'border-color: transparent;'}
      - if @user_group.topics.present?
        - @user_group.topics.each do |topic|
          %span.tags
            %span.glyphicons.tag
            = topic

    %hr

    = link_to @user_group.homepage, target: '_blank', 'itemprop' => 'url' do
      %span.glyphicons.home
      = @user_group.name
      Homepage

    %hr

    = render 'twitter_button', model: @user_group

    - unless @user_group.networks.empty?
      %hr

      %h4 Network Affiliations:
      - @user_group.networks.each do |network|
        %div= link_to(network.name, network_path(network))

- if current_user && (current_user.admin? || current_user == @user_group.registered_by)
  .col-lg-6
    .btn-group
      %button.btn.btn-default.dropdown-toggle{"data-toggle" => "dropdown", type: "button"}
        Manage User-Group
        %span.caret
      %ul.dropdown-menu{role: "menu"}
        %li= link_to 'Edit', edit_user_group_path(@user_group)
        %li= link_to 'Destroy', @user_group, method: :delete, data: {confirm: 'Are you sure?'}

#user_group_members.col-lg-6
  %h4 User-Group Membership:
  = render 'join_leave'
  %ul.media-list
    - @ugms.map { |ugm| ugm.user }.each do |user|
      %li.media
        = link_to profile_path(user), class: 'pull-left' do
          = gravatar_image_tag(user.email, size: 64, style: 'height: 64px; width: 64px', alt: user.profile.preferred_name_or_username, alt: user.profile.preferred_name_or_username, class: '')
        .media-body
          %h4= link_to user.profile.preferred_name_or_username, profile_path(user)
          %p.description= Sanitize.clean(user.profile.bio || '', Sanitize::Config::BASIC).truncate(64)
          - if user.profile.interests.present?
            - user.profile.interests.each do |interest|
              %span.tags
                %span.glyphicons.tag
                = interest