config/routes.rb
# frozen_string_literal: true
require 'sidekiq/web'

# 127.0.0.1 uglst.dev
# 127.0.0.1 api.uglst.dev

Rails.application.routes.draw do
  use_doorkeeper

  resources :opportunities, only: %i(index show)

  # /status
  get '/status', to: 'status#ping'

  # /heartbeat
  get '/heartbeat.:format', to: 'heartbeat#ping', constraints: { format: 'txt' }

  get 'reports/top_viewed_user_groups.:format', to: 'reports#top_viewed_user_groups', constraints: { format: 'json' }

  namespace :happy do
    get 'hello/badge'
  end

  authenticate :user, ->(u) { Rails.env.development? || u.admin? } do
    namespace :admin, path: '/admin' do # , constraints: require_admin do
      mount Sidekiq::Web, at: 'sidekiq'
      mount PgHero::Engine, at: 'pghero'
      mount RailsAdmin::Engine, at: 'rails'
    end
  end

  namespace :api, path: '/', constraints: { subdomain: 'api' } do
    namespace :v1 do
      get '/me' => 'credentials#me'
    end
  end

  # /privacy
  get 'privacy' => 'pages#privacy'

  # /terms_of_service
  get 'terms_of_service' => 'pages#terms_of_service'

  post 'awesome' => 'pages#awesome'

  # /networks
  resources :networks

  resources :profiles, except: %(edit update destroy) do
    scope module: :profiles do
      # /profiles/:id/account
      resource :account, only: %i(edit update)

      # /profiles/:id/private
      resource :private, only: %i(edit update destroy)

      # /profiles/:id/public
      resource :public, only: %i(edit update)
    end
  end

  # /users
  devise_for :users

  resources :user_groups do
    # /user_groups/:id/join
    post '/join' => 'user_groups#join'

    # /user_groups/:id/leave
    post '/leave' => 'user_groups#leave'

    # /user_groups/:id/memberships
    get '/memberships' => 'user_groups#memberships'
  end

  # /
  root 'user_groups#index'
end

# == Route Map
#
#                        Prefix Verb   URI Pattern                                       Controller#Action
#                               GET    /oauth/authorize/:code(.:format)                  doorkeeper/authorizations#show
#           oauth_authorization GET    /oauth/authorize(.:format)                        doorkeeper/authorizations#new
#                               POST   /oauth/authorize(.:format)                        doorkeeper/authorizations#create
#                               DELETE /oauth/authorize(.:format)                        doorkeeper/authorizations#destroy
#                   oauth_token POST   /oauth/token(.:format)                            doorkeeper/tokens#create
#                  oauth_revoke POST   /oauth/revoke(.:format)                           doorkeeper/tokens#revoke
#            oauth_applications GET    /oauth/applications(.:format)                     doorkeeper/applications#index
#                               POST   /oauth/applications(.:format)                     doorkeeper/applications#create
#         new_oauth_application GET    /oauth/applications/new(.:format)                 doorkeeper/applications#new
#        edit_oauth_application GET    /oauth/applications/:id/edit(.:format)            doorkeeper/applications#edit
#             oauth_application GET    /oauth/applications/:id(.:format)                 doorkeeper/applications#show
#                               PATCH  /oauth/applications/:id(.:format)                 doorkeeper/applications#update
#                               PUT    /oauth/applications/:id(.:format)                 doorkeeper/applications#update
#                               DELETE /oauth/applications/:id(.:format)                 doorkeeper/applications#destroy
# oauth_authorized_applications GET    /oauth/authorized_applications(.:format)          doorkeeper/authorized_applications#index
#  oauth_authorized_application DELETE /oauth/authorized_applications/:id(.:format)      doorkeeper/authorized_applications#destroy
#              oauth_token_info GET    /oauth/token/info(.:format)                       doorkeeper/token_info#show
#                 opportunities GET    /opportunities(.:format)                          opportunities#index
#                   opportunity GET    /opportunities/:id(.:format)                      opportunities#show
#                        status GET    /status(.:format)                                 status#ping
#                               GET    /heartbeat.:format                                heartbeat#ping {:format=>"txt"}
#                               GET    /reports/top_viewed_user_groups.:format           reports#top_viewed_user_groups {:format=>"json"}
#             happy_hello_badge GET    /happy/hello/badge(.:format)                      happy/hello#badge
#             admin_sidekiq_web        /admin/sidekiq                                    Sidekiq::Web
#                 admin_pg_hero        /admin/pghero                                     PgHero::Engine
#             admin_rails_admin        /admin/rails                                      RailsAdmin::Engine
#                     api_v1_me GET    /v1/me(.:format)                                  api/v1/credentials#me {:subdomain=>"api"}
#                       privacy GET    /privacy(.:format)                                pages#privacy
#              terms_of_service GET    /terms_of_service(.:format)                       pages#terms_of_service
#                       awesome POST   /awesome(.:format)                                pages#awesome
#                      networks GET    /networks(.:format)                               networks#index
#                               POST   /networks(.:format)                               networks#create
#                   new_network GET    /networks/new(.:format)                           networks#new
#                  edit_network GET    /networks/:id/edit(.:format)                      networks#edit
#                       network GET    /networks/:id(.:format)                           networks#show
#                               PATCH  /networks/:id(.:format)                           networks#update
#                               PUT    /networks/:id(.:format)                           networks#update
#                               DELETE /networks/:id(.:format)                           networks#destroy
#          edit_profile_account GET    /profiles/:profile_id/account/edit(.:format)      profiles/account#edit
#               profile_account PATCH  /profiles/:profile_id/account(.:format)           profiles/account#update
#                               PUT    /profiles/:profile_id/account(.:format)           profiles/account#update
#          edit_profile_private GET    /profiles/:profile_id/private/edit(.:format)      profiles/private#edit
#               profile_private PATCH  /profiles/:profile_id/private(.:format)           profiles/private#update
#                               PUT    /profiles/:profile_id/private(.:format)           profiles/private#update
#                               DELETE /profiles/:profile_id/private(.:format)           profiles/private#destroy
#           edit_profile_public GET    /profiles/:profile_id/public/edit(.:format)       profiles/public#edit
#                profile_public PATCH  /profiles/:profile_id/public(.:format)            profiles/public#update
#                               PUT    /profiles/:profile_id/public(.:format)            profiles/public#update
#                      profiles GET    /profiles(.:format)                               profiles#index
#                               POST   /profiles(.:format)                               profiles#create
#                   new_profile GET    /profiles/new(.:format)                           profiles#new
#                  edit_profile GET    /profiles/:id/edit(.:format)                      profiles#edit
#                       profile GET    /profiles/:id(.:format)                           profiles#show
#                               PATCH  /profiles/:id(.:format)                           profiles#update
#                               PUT    /profiles/:id(.:format)                           profiles#update
#                               DELETE /profiles/:id(.:format)                           profiles#destroy
#              new_user_session GET    /users/sign_in(.:format)                          devise/sessions#new
#                  user_session POST   /users/sign_in(.:format)                          devise/sessions#create
#          destroy_user_session DELETE /users/sign_out(.:format)                         devise/sessions#destroy
#                 user_password POST   /users/password(.:format)                         devise/passwords#create
#             new_user_password GET    /users/password/new(.:format)                     devise/passwords#new
#            edit_user_password GET    /users/password/edit(.:format)                    devise/passwords#edit
#                               PATCH  /users/password(.:format)                         devise/passwords#update
#                               PUT    /users/password(.:format)                         devise/passwords#update
#      cancel_user_registration GET    /users/cancel(.:format)                           devise/registrations#cancel
#             user_registration POST   /users(.:format)                                  devise/registrations#create
#         new_user_registration GET    /users/sign_up(.:format)                          devise/registrations#new
#        edit_user_registration GET    /users/edit(.:format)                             devise/registrations#edit
#                               PATCH  /users(.:format)                                  devise/registrations#update
#                               PUT    /users(.:format)                                  devise/registrations#update
#                               DELETE /users(.:format)                                  devise/registrations#destroy

app/views/layouts/_breadcrumb.html.haml
%ol.breadcrumb
  %li
    = link_to root_path do
      %span.glyphicons.home
      Home
  = yield :breadcrumb

app/views/layouts/_favicons.html.erb
<link rel="shortcut icon" href="/favicon.ico" type="image/x-icon"/>
<!-- Apple Touch Icons -->
<link rel="apple-touch-icon" href="/apple-touch-icon.png"/>
<link rel="apple-touch-icon" sizes="57x57" href="/apple-touch-icon-57x57.png"/>
<link rel="apple-touch-icon" sizes="72x72" href="/apple-touch-icon-72x72.png"/>
<link rel="apple-touch-icon" sizes="114x114" href="/apple-touch-icon-114x114.png"/>
<link rel="apple-touch-icon" sizes="144x144" href="/apple-touch-icon-144x144.png"/>
<link rel="apple-touch-icon" sizes="60x60" href="/apple-touch-icon-60x60.png"/>
<link rel="apple-touch-icon" sizes="120x120" href="/apple-touch-icon-120x120.png"/>
<link rel="apple-touch-icon" sizes="76x76" href="/apple-touch-icon-76x76.png"/>
<link rel="apple-touch-icon" sizes="152x152" href="/apple-touch-icon-152x152.png"/>
<!-- Windows 8 Tile Icons -->
<meta name="msapplication-square70x70logo" content="smalltile.png"/>
<meta name="msapplication-square150x150logo" content="mediumtile.png"/>
<meta name="msapplication-wide310x150logo" content="widetile.png"/>
<meta name="msapplication-square310x310logo" content="largetile.png"/>

app/views/layouts/_flash.html.haml
- flash.each do |name, msg|
  - if msg.is_a?(String)
    %div{class: "alert alert-#{name.to_s == 'notice' ? 'success' : 'danger'}"}
      %button.close{"aria-hidden" => "true", "data-dismiss" => "alert", type: "button"} &times;
      = content_tag :div, msg, id: "flash_#{name}"

app/views/layouts/_footer.html.haml
.footer.col-lg-12
  .row
    .col-md-3(style="background-color: rgba(255, 255, 255, 0.84); height: 176px;")
      %ul.list-unstyled
        %li.h4 User-Group List
        %li
          = link_to user_groups_path do
            %span.glyphicons.list
            User-Groups List
        %li
          = link_to profiles_path do
            %span.glyphicons.group
            Member Directory
        %li
          %a{href: 'http://www.ugtastic.com'}
            %span.glyphicons.film
            Community Interviews
        %li
          = link_to user_groups_url(format: :rss) do
            %span.social.rss
            User-Groups RSS
    -#.col-md-3
      -#%ul.list-unstyled
        -#%li.h4 Help for…
        -#%li
          -#%a{href: '#'}
            -#%span.glyphicons.girl
            -#User-Group Organizers
        -#%li
          -#%a{href: '#'}
            -#%span.glyphicons.glyphicons.group
            -#Community Members
        -#%li
          -#%a{href: '#'}
            -#%span.glyphicons.briefcase
            -#Recruiters &amp; Marketers
    .col-md-3(style="background-color: rgba(255, 255, 255, 0.84); height: 176px;")
      %ul.list-unstyled
        %li.h4 Account
        - if current_user
          %li
            = link_to edit_profile_public_path(current_user.profile) do
              %span.glyphicons.girl
              = current_user.username || 'Username?'
          %li
            = link_to destroy_user_session_path, method: :delete do
              %span.glyphicons.log_out
              Sign out
        - else
          %li
            = link_to new_registration_path(User) do
              %span.glyphicons.user_add
              Sign up
          %li
            = link_to new_session_path(User) do
              %span.glyphicons.log_in
              Sign in
    .col-md-6(style="background-color: rgba(255, 255, 255, 0.84); height: 176px;")
      - unless current_page?(root_path)
        %ul.list-unstyled
          %li
            .h3 Add your favorite User-Group to the User-Group List today.
            %p.description Free tweet for your user-group automatically on registration.
            = link_to new_user_group_path, class: 'btn btn-danger', style: 'color: white; font-weight: bold' do
              %span.glyphicons.plus
              Register a User-Group!


  .row
    .col-md-8(style="background-color: rgba(255, 255, 255, 0.84); height: 32px")
      .btn-group-xs{role: 'group'}
        = link_to 'Terms of Service', terms_of_service_path, class: 'btn btn-default'
        = link_to 'Privacy', privacy_path, class: 'btn btn-default'
    .col-md-4(style="background-color: white; height: 32px;")
      %p.muted.pull-right
        © 2015
        = succeed '.' do
          %a{href: 'mailto:mike@ugtastic.com'} UGtastic
        All rights reserved

app/views/layouts/_google_analytics.html.erb
<script>
    (function (i, s, o, g, r, a, m) {
        i['GoogleAnalyticsObject'] = r;
        i[r] = i[r] || function () {
            (i[r].q = i[r].q || []).push(arguments)
        }, i[r].l = 1 * new Date();
        a = s.createElement(o),
                m = s.getElementsByTagName(o)[0];
        a.async = 1;
        a.src = g;
        m.parentNode.insertBefore(a, m)
    })(window, document, 'script', '//www.google-analytics.com/analytics.js', 'ga');

    <%- if current_user -%>
    ga('create', '<%= ENV['GOOGLE_ANALYTICS_TRACKING_ID'] -%>', 'auto', {'userId': '<%= current_user.id -%>'});
    <%- else -%>
    ga('create', '<%= ENV['GOOGLE_ANALYTICS_TRACKING_ID'] -%>', 'auto');
    <%- end -%>
    ga('require', 'linkid', 'linkid.js');
    ga('require', 'displayfeatures');
    <%- if current_user -%>
    ga('set', '&uid', '<%= current_user.id -%>'); // Set the user ID using signed-in user_id.
    <%- end -%>
    ga('send', 'pageview');

</script>

app/views/layouts/_head.html.haml
%head
  %meta{charset: 'utf-8'}
  %meta{content: 'IE=edge', 'http-equiv' => 'X-UA-Compatible'}
  %meta{content: 'width=device-width, initial-scale=1', name: 'viewport'}
  %meta{content: @description || 'Connecting user-group organizers with the members of their community and the sponsors who help fund them.', name: 'description'}
  %meta{content: 'https://plus.google.com/117224417942370890949', name: 'author'}
  = yield :twitter_card
  %title= @page_title || 'User-Group List by UGtastic'
  = render 'layouts/google_analytics'
  = render 'layouts/favicons'
  = stylesheet_link_tag 'application', media: 'all'
  = stylesheet_link_tag controller_name, media: 'all'
  %script{src: '//maps.googleapis.com/maps/api/js?libraries=places&sensor=false'}
  %script{src: '//google-maps-utility-library-v3.googlecode.com/svn/tags/markerclustererplus/2.0.14/src/markerclusterer_packed.js'}
  = javascript_include_tag 'application', controller_name
  = csrf_meta_tags
  / HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries
  / WARNING: Respond.js doesn't work if you view the page via file://
  /[if lt IE 9]
    <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
  <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
  = yield :javascript
  = yield :rss

app/views/layouts/_nav_bar.html.haml
.navbar.navbar-inverse.navbar-fixed-top{:role => "navigation"}
  .container
    .navbar-header
      %button.navbar-toggle{"data-target" => ".navbar-collapse", "data-toggle" => "collapse", :type => "button"}
        %span.sr-only Toggle navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      = link_to 'User-Group List', root_path, class: 'navbar-brand'
    .collapse.navbar-collapse
      %ul.nav.navbar-nav
      .col-sm-3.col-md-3
        %form.navbar-form{:role => "search"}
          .input-group
            %input.form-control{:name => "q", :placeholder => "Search User-Groups", :type => "text"}
            .input-group-btn
              %button.btn.btn-default{:type => "submit"}
                %i.glyphicons.search
      %ul.nav.navbar-nav.navbar-right
        %li
          = link_to user_groups_path do
            %span.glyphicons.list
            User-Groups
        %li#nav-register-ug-btn
        - if current_user
          %li#nav-profile-btn
            = link_to profile_path(current_user) do
              %span.glyphicons.user
              = current_user.username || 'Username?'
          %li#nav-signout-btn
            = link_to destroy_user_session_path, method: :delete do
              %span.glyphicons.log_out
              Sign out
        - else
          %li#nav-register-btn
            = link_to new_registration_path(User) do
              %span.glyphicons.user_add
              Sign up
          %li#nav-login-btn
            = link_to new_session_path(User) do
              %span.glyphicons.log_in
              Sign in

app/views/layouts/application.html.haml
!!!
%html{lang: 'en'}
  = render 'layouts/head'
  %body
    = render 'layouts/nav_bar'
    .container
      = render 'layouts/breadcrumb'
      = render partial: 'layouts/flash'
      - if current_user && current_user.username.blank?
        .alert.alert-warning
          %button.close{'aria-hidden' => 'true', 'data-dismiss' => 'alert', type: 'button'} &times;
          = content_tag :div, id: 'flash_warning' do
            Looks like your username is blank. Click to #{link_to 'set your username', edit_profile_account_path(current_user.profile), class: 'btn btn-default', id: 'set-your-username'}
      = yield
      = render 'layouts/footer'

app/views/layouts/devise.html.haml
!!!
%html{:lang => "en"}
  = render 'layouts/head'
  %body
    .container
      #wrap.container
        .row
          .col-md-6.col-md-offset-3
            = render partial: 'layouts/flash'
      = yield

app/views/layouts/happy.html.haml
!!!
%html{lang: 'en'}
  %head
    %meta{charset: 'utf-8'}
    %meta{content: 'IE=edge', 'http-equiv' => 'X-UA-Compatible'}
    %meta{content: 'width=device-width, initial-scale=1', name: 'viewport'}
    %meta{content: @description || 'Connecting user-group organizers with the members of their community and the sponsors who help fund them.', name: "description"}
    %meta{content: 'https://plus.google.com/117224417942370890949', name: 'author'}
    -#= yield :twitter_card
    %title= @page_title || 'User-Group List by UGtastic'
    -#= render 'layouts/google_analytics'
    = stylesheet_link_tag 'happy', media: 'all'
    %script{src: "//maps.google.com/maps/api/js?v=3.13&amp;sensor=false&amp;libraries=geometry", type: "text/javascript"}
    %script{src: "//google-maps-utility-library-v3.googlecode.com/svn/tags/markerclustererplus/2.0.14/src/markerclusterer_packed.js", type: "text/javascript"}
    = javascript_include_tag 'happy', "happy/#{controller_name}"
    = csrf_meta_tags
    / HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries
    / WARNING: Respond.js doesn't work if you view the page via file://
    /[if lt IE 9]
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
    <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    = yield :javascript
  %body
    = yield

app/views/layouts/root.html.haml
!!!
%html{lang: 'en'}
  = render 'layouts/head'
  :javascript
     $(document).ready(function () { });

%body
  = render 'layouts/nav_bar'
  .container
    #googlemaps
      = render partial: 'layouts/flash'
    .col-lg-12
      = yield
    = render 'layouts/footer'